In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
#-----------creating one dimention array------------

In [4]:
D1 = np.array([1,2,3])
D1

array([1, 2, 3])

In [5]:
print(np.ndim(D1))

1


In [6]:
#--------------creating two dimention array-----------------

In [7]:
D2 = np.array([[1,2],[3,4]])
D2

array([[1, 2],
       [3, 4]])

In [8]:
print(np.ndim(D2))

2


In [9]:
#----------------creating three dimention array--------------

In [10]:
D3 = np.array([[[19,65,43],[7,8,9],[11,12,13]]])
D3

array([[[19, 65, 43],
        [ 7,  8,  9],
        [11, 12, 13]]])

In [11]:
print(np.ndim(D3))

3


In [12]:
#---------------creating four dimention array-------------------

In [13]:
D4 = np.array([[[[1,2,3,4],[4,5,6,7],[6,7,8,9],[4,8,9,5]]]])
D4

array([[[[1, 2, 3, 4],
         [4, 5, 6, 7],
         [6, 7, 8, 9],
         [4, 8, 9, 5]]]])

In [14]:
print(np.ndim(D4))

4


In [15]:
#------------------creating five dimention array----------------

In [16]:
D5 = np.array([[[[[1,2,3,4,15],[2,23,44,5,16],[32,14,51,6,7],[1,2,3,7,8],[11,12,13,14,15]]]]])
D5

array([[[[[ 1,  2,  3,  4, 15],
          [ 2, 23, 44,  5, 16],
          [32, 14, 51,  6,  7],
          [ 1,  2,  3,  7,  8],
          [11, 12, 13, 14, 15]]]]])

In [17]:
print(np.ndim(D5))

5


In [18]:
#-------------------finding det for 5 matrices-------------------

In [19]:
import numpy as np
from numpy import linalg as la

In [20]:
#det1 = la.det(D1)  #gives u a error
det2 = la.det(D2)
det2

-2.0000000000000004

In [21]:
det3 = la.det(D3)
det3

array([272.])

In [22]:
det4 = la.det(D4)
det4

array([[1.33226763e-14]])

In [23]:
det5=la.det(D5)
det5

array([[[-724350.]]])

In [24]:
#---------------finding transpose of the matrix---------------

In [25]:
print(D1.T)

[1 2 3]


In [26]:
print(D2.T)

[[1 3]
 [2 4]]


In [27]:
print(D3.T)

[[[19]
  [ 7]
  [11]]

 [[65]
  [ 8]
  [12]]

 [[43]
  [ 9]
  [13]]]


In [28]:
print(D4.T)

[[[[1]]

  [[4]]

  [[6]]

  [[4]]]


 [[[2]]

  [[5]]

  [[7]]

  [[8]]]


 [[[3]]

  [[6]]

  [[8]]

  [[9]]]


 [[[4]]

  [[7]]

  [[9]]

  [[5]]]]


In [29]:
print(D5.T)

[[[[[ 1]]]


  [[[ 2]]]


  [[[32]]]


  [[[ 1]]]


  [[[11]]]]



 [[[[ 2]]]


  [[[23]]]


  [[[14]]]


  [[[ 2]]]


  [[[12]]]]



 [[[[ 3]]]


  [[[44]]]


  [[[51]]]


  [[[ 3]]]


  [[[13]]]]



 [[[[ 4]]]


  [[[ 5]]]


  [[[ 6]]]


  [[[ 7]]]


  [[[14]]]]



 [[[[15]]]


  [[[16]]]


  [[[ 7]]]


  [[[ 8]]]


  [[[15]]]]]


In [30]:
#print(la.inv(D1))
print(la.inv(D2))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [31]:
print(la.inv(D3))

[[[-0.01470588 -1.20955882  0.88602941]
  [ 0.02941176 -0.83088235  0.47794118]
  [-0.01470588  1.79044118 -1.11397059]]]


In [32]:
print(la.inv(D4))

[[[[ 7.50599938e+14 -1.87649984e+15  1.12589991e+15  8.33333333e-02]
   [-1.95155984e+15  4.87889960e+15 -2.92733976e+15 -4.16666667e-01]
   [ 1.65131986e+15 -4.12829966e+15  2.47697980e+15  5.83333333e-01]
   [-4.50359963e+14  1.12589991e+15 -6.75539944e+14 -2.50000000e-01]]]]


In [33]:
print(la.inv(D5))

[[[[[ 3.48339891e-02 -3.06205564e-02  1.81818182e-02 -1.15441430e-01
      5.09118520e-02]
    [-9.15165321e-03  2.17574377e-02 -3.63636364e-02 -2.25457307e-01
      1.23157313e-01]
    [-2.03672258e-02  1.41782288e-02  1.81818182e-02  1.13867605e-01
     -6.39704563e-02]
    [-1.05315110e-01 -5.31511010e-03 -2.41810074e-20  2.27031131e-01
     -1.00987092e-02]
    [ 9.77220957e-02 -2.27790433e-03 -1.03632889e-20 -4.55580866e-02
     -4.32801822e-03]]]]]


In [34]:
#---------------finding trace of the matrix-------------------

In [35]:
#print(np.trace(D1))
print(np.trace(D2))
print(np.trace(D3))
print(np.trace(D4))
print(np.trace(D5))

5
[19 65 43]
[[1 2 3 4]
 [4 5 6 7]
 [6 7 8 9]
 [4 8 9 5]]
[[[ 1  2  3  4 15]
  [ 2 23 44  5 16]
  [32 14 51  6  7]
  [ 1  2  3  7  8]
  [11 12 13 14 15]]]


In [36]:
#-----------------finding rank of the matrix--------------------

In [37]:
print(la.matrix_rank(D1))
print(la.matrix_rank(D2))
print(la.matrix_rank(D3))
print(la.matrix_rank(D4))
print(la.matrix_rank(D5))

1
2
[3]
[[3]]
[[[5]]]


In [38]:
#-------------------finding diagonals of the matrix----------------

In [39]:
print(np.diag(D1))
print(np.diag(D2))
#print(np.diag(D3))
#print(np.diag(D4))
#print(np.diag(D5)) it gives error for D3 and more dimentions

[[1 0 0]
 [0 2 0]
 [0 0 3]]
[1 4]


In [40]:
#------------------finding eigen values and eigen vectors--------------

In [41]:
#print(la.eigvals(D1)) error
print(la.eigvals(D2))
print(la.eigvals(D3))
print(la.eigvals(D4))
print(la.eigvals(D5))

[-0.37228132  5.37228132]
[[ 50.63285827 -10.1010308   -0.53182747]]
[[[ 2.33876857e+01 -2.63558006e+00 -1.75210566e+00 -7.98944552e-16]]]
[[[[ 74.94297768+0.j          14.26053623+7.67083299j
     14.26053623-7.67083299j -10.11009509+0.j
      3.64604495+0.j        ]]]]


In [42]:
#x,y=la.eig(D1)
#print("Values:",x)
#print("vectors:",y)

In [43]:
x,y=la.eig(D2)
print("eigen Values:",x)
print("eigen vectors:",y)

eigen Values: [-0.37228132  5.37228132]
eigen vectors: [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [44]:
x,y=la.eig(D3)
print("eigen Values:",x)
print("eigen vectors:",y)

eigen Values: [[ 50.63285827 -10.1010308   -0.53182747]]
eigen vectors: [[[-0.9146971  -0.92111118 -0.57007616]
  [-0.22154136  0.18623201 -0.32723971]
  [-0.33800686  0.34186522  0.75360954]]]


In [45]:
x,y=la.eig(D4)
print("eigen Values:",x)
print("eigen vectors:",y)

eigen Values: [[[ 2.33876857e+01 -2.63558006e+00 -1.75210566e+00 -7.98944552e-16]]]
eigen vectors: [[[[ 0.22854499 -0.56583976 -0.78880879  0.27777778]
   [ 0.4726279  -0.3007259  -0.23060725 -0.72222222]
   [ 0.63534983 -0.12398332  0.1415271   0.61111111]
   [ 0.56632204  0.75763938  0.55187958 -0.16666667]]]]


In [46]:
x,y=la.eig(D5)
print("eigen Values:",x)
print("eigen vectors:",y)

eigen Values: [[[[ 74.94297768+0.j          14.26053623+7.67083299j
     14.26053623-7.67083299j -10.11009509+0.j
      3.64604495+0.j        ]]]]
eigen vectors: [[[[[ 0.11394133+0.j         -0.26240853-0.24524872j
     -0.26240853+0.24524872j -0.49353443+0.j
      0.22592903+0.j        ]
    [ 0.66776149+0.j          0.75539088+0.j
      0.75539088-0.j         -0.64553819+0.j
      0.67033752+0.j        ]
    [ 0.65762217+0.j         -0.06460707+0.29425416j
     -0.06460707-0.29425416j  0.37377786+0.j
     -0.29855655+0.j        ]
    [ 0.08777968+0.j         -0.16970224-0.14259799j
     -0.16970224+0.14259799j -0.15701881+0.j
     -0.61643561+0.j        ]
    [ 0.31771021+0.j         -0.14910449-0.37182614j
     -0.14910449+0.37182614j  0.4187355 +0.j
      0.17457036+0.j        ]]]]]


In [47]:
#-----------------finding Sum(),cumsum(),min(),max(),count(),mode(),median(),describe()-----------------

In [48]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [49]:
import pandas as pd

In [50]:
df={'Name':pd.Series(['Sai','hema','latha','madhu','surekha','ram','raja','siri']),
    'Age':pd.Series([10,16,15,18,23,25,30,35]),
    'Weight':pd.Series([10,35,35,38,40,50,55,60])
   }

In [51]:
df=pd.DataFrame(df)
df

Name  Age  Weight
0      Sai   10      10
1     hema   16      35
2    latha   15      35
3    madhu   18      38
4  surekha   23      40
5      ram   25      50
6     raja   30      55
7     siri   35      60

In [52]:
print(df.sum())

Name      Saihemalathamadhusurekharamrajasiri
Age                                       172
Weight                                    323
dtype: object


In [53]:
print(df.cumsum())

                                  Name  Age  Weight
0                                  Sai   10      10
1                              Saihema   26      45
2                         Saihemalatha   41      80
3                    Saihemalathamadhu   59     118
4             Saihemalathamadhusurekha   82     158
5          Saihemalathamadhusurekharam  107     208
6      Saihemalathamadhusurekharamraja  137     263
7  Saihemalathamadhusurekharamrajasiri  172     323


In [54]:
df1={
    'Age':pd.Series([10,16,15,18,23,25,30,35]),
    'Weight':pd.Series([10,35,35,38,40,50,55,60])
}
df1=pd.DataFrame(df1)
df1

Age  Weight
0   10      10
1   16      35
2   15      35
3   18      38
4   23      40
5   25      50
6   30      55
7   35      60

In [55]:
print(df1.mean())

Age       21.500
Weight    40.375
dtype: float64


In [56]:
print(df1.median())

Age       20.5
Weight    39.0
dtype: float64


In [57]:
print(df1.mode())

   Age  Weight
0   10    35.0
1   15     NaN
2   16     NaN
3   18     NaN
4   23     NaN
5   25     NaN
6   30     NaN
7   35     NaN


In [58]:
print(df1.describe())

             Age     Weight
count   8.000000   8.000000
mean   21.500000  40.375000
std     8.332381  15.482133
min    10.000000  10.000000
25%    15.750000  35.000000
50%    20.500000  39.000000
75%    26.250000  51.250000
max    35.000000  60.000000


In [59]:
print(df1.max())

Age       35
Weight    60
dtype: int64


In [60]:
print(df1.min())

Age       10
Weight    10
dtype: int64


In [61]:
print(df1.count())

Age       8
Weight    8
dtype: int64


In [62]:
#---------------finding covariance and correlation----------------

In [63]:
pip install scipy 

Note: you may need to restart the kernel to use updated packages.


In [64]:
from numpy import cov
data1=[1,2,3,4,5,6,7,8,9,10]
data2=[11,22,33,44,55,66,77,88,99,19]
covariance=cov(data1,data2)
print(covariance)

[[  9.16666667  55.33333333]
 [ 55.33333333 936.26666667]]


In [65]:
from scipy.stats import pearsonr
data1=[1,2,3,4,5,6,7,8,9,10]
data2=[11,22,33,44,55,66,77,88,99,19]
corr=pearsonr(data1,data2)
print(corr)

PearsonRResult(statistic=0.5972846214175458, pvalue=0.06825702065969003)
